name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          git clone https://github.com/deshpandetanmay/git-secrets.git
          cd git-secrets
          sudo make install
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          git secrets --install
          git secrets --register-aws
          git secrets --scan
          if [ $? -eq 0 ]; then
              echo "git secrets --scan OK"
          else
              echo "git secrets --scan FAIL"
      - run: echo "This job's status is ${{ job.status }}."