name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
      - name: Scan secrets in the repository
        run: |
          git secrets --install
          git secrets --add-provider -- git secrets --aws-provider
          git secrets --register-aws
          git secrets --scan -r ${{ github.workspace }}/*
          if [[ $? -eq 0 ]]; then
              echo "git secrets --scan OK"
          else
              echo "git secrets --scan FAIL"
          fi