name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Find Secrets
        jobs:
          main:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v2
              - uses: max/secret-scan@master