name: GitHub Actions Demo
on: [push]
jobs:
  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v2

      # Scan Secrets
      - name: Scan for Secrets
        uses: max/secret-scan@master

      # Install Go.
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14" # The Go version to download and use.
          
      - name: Print Go version
        run: go version

      # Run unit tests.
      - name: Run unit tests
        run: go test -v ./...